language: node_js
node_js:
  - "6"
  - "7"
notifications:
  email: false
  webhooks: https://serabxudzb.localtunnel.me/travis-ci/eva-dev
after_success:
  - npm run coveralls
  - npm run codeclimate
cache: yarn
